### ISSUE TITLE
Dr Mario. Online Rx. Fails

### ISSUE THREAD

**Issue by PokeAcer** [sepalani/GamestatsHTTP#19]
Logs
```[drmariowii] GET /web/client/get2.asp?pid=600235521
Key: GamestatsKey(salt='FRFCvNXiZGQgfbWudVoP', constants=GamestatsKeyConstants(x=210477, y=25691, z=131072, checksum_secret=1725970804))
[drmariowii] Handle get2.asp?pid=600235521
127.0.0.1 - - [02/Jul/2017 22:23:17] "GET /drmariowii/web/client/get2.asp?pid=600235521 HTTP/1.1" 200 -
[drmariowii] GET /web/client/get2.asp?pid=600235521&hash=db52b13ebd843bdc6f6c9b459e37799a883a75dd&data=ZuA7jwDfxyIdAAEB_gEAAAEAAQABAAEBDAABAQAAAQAKAQEBAQEAAQ==
Key: GamestatsKey(salt='FRFCvNXiZGQgfbWudVoP', constants=GamestatsKeyConstants(x=210477, y=25691, z=131072, checksum_secret=1725970804))
[drmariowii] Handle get2.asp?pid=600235521&hash=db52b13ebd843bdc6f6c9b459e37799a883a75dd&data=ZuA7jwDfxyIdAAEB_gEAAAEAAQABAAEBDAABAQAAAQAKAQEBAQEAAQ==
127.0.0.1 - - [02/Jul/2017 22:23:17] Get2 request for drmariowii: {'hash': ['db52b13ebd843bdc6f6c9b459e37799a883a75dd'], 'pid': ['600235521'], 'data': ['ZuA7jwDfxyIdAAEB_gEAAAEAAQABAAEBDAABAQAAAQAKAQEBAQEAAQ==']}
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 51808)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "gamestats_server.py", line 61, in do_GET
    self.server.gamestats_router.do_GET(self, gamename, path)
  File "/home/billy/services/HTTPGameStats/project/routers/__init__.py", line 31, in <lambda>
    self.do(handler, gamename, path, routes)
  File "/home/billy/services/HTTPGameStats/project/routers/__init__.py", line 39, in do
    return callback(handler, gamename, resource)
  File "/home/billy/services/HTTPGameStats/project/routers/web.py", line 404, in handle_web_client
    "put2.asp": client_put2
  File "/home/billy/services/HTTPGameStats/project/routers/web.py", line 379, in handle
    callback(handler, gamename, resource)
  File "/home/billy/services/HTTPGameStats/project/routers/web.py", line 259, in client_get2
    handler.server.gamestats_db
  File "/home/billy/services/HTTPGameStats/project/gamestats_database.py", line 215, in web_get2
    return db.web_get2(gamename, pid, region, category, mode, data)
  File "/home/billy/services/HTTPGameStats/project/gamestats_database.py", line 193, in web_get2
    raise ValueError("Unknown get2 mode: {}".format(mode))
ValueError: Unknown get2 mode: 4228141133
```

**Comment by sepalani** [comment]
The decoded data is:
```
00000000  66 e0 3b 8f 00 df c7 22  1d 00 01 01 fe 01 00 00  |f.;...."........|
00000010  01 00 01 00 01 00 01 01  0c 00 01 01 00 00 01 00  |................|
00000020  0a 01 01 01 01 01 00 01                           |........|
00000028
```
The expected pid is 0x01dec623 but 0x00dfc722 is found instead.

Sounds similar to issue https://github.com/sepalani/GamestatsHTTP/issues/20

**Comment by sepalani** [comment]
It should be fixed by: https://github.com/sepalani/GamestatsHTTP/commit/0a03ae8a7ca4fbc4ef7c0370b1ba69de67de3759.
