### ISSUE TITLE
tatvscapwii Issue

### ISSUE THREAD

**Issue by ghost** [sepalani/GamestatsHTTP#22]
***NOTE***: The game will actually download and save the rankings, but gives a 98870 error while doing so.

Log:
```127.0.0.1 - - [02/Jul/2017 22:50:30] "GET /tatvscapwii/web/client/get2.asp?pid=600259714&hash=fe566be37a8334dd810d32ac5160e75323ba9cb9&data=aFtngYI8xyMcAAAA_wAAAAAAAAABAAAADAAAAAEAAAAUAAAAAAAAAA== HTTP/1.1" 200 -
[tatvscapwii] GET /web/client/get2.asp?pid=600259714
Key: GamestatsKey(salt='QFFeWypIFepXgAhZxeNy', constants=GamestatsKeyConstants(x=126373, y=13797, z=8192, checksum_secret=1750820196))
[tatvscapwii] Handle get2.asp?pid=600259714
127.0.0.1 - - [02/Jul/2017 22:50:30] "GET /tatvscapwii/web/client/get2.asp?pid=600259714 HTTP/1.1" 200 -
[tatvscapwii] GET /web/client/get2.asp?pid=600259714&hash=d814efa0880aec2d6ac2b2fc7a6de28a72c52e56&data=aFtns4I8xyMcAAAA_wAAAAAAAAAFAAAADAAAAAEAAAACAAAAAAAAAA==
Key: GamestatsKey(salt='QFFeWypIFepXgAhZxeNy', constants=GamestatsKeyConstants(x=126373, y=13797, z=8192, checksum_secret=1750820196))
[tatvscapwii] Handle get2.asp?pid=600259714&hash=d814efa0880aec2d6ac2b2fc7a6de28a72c52e56&data=aFtns4I8xyMcAAAA_wAAAAAAAAAFAAAADAAAAAEAAAACAAAAAAAAAA==
127.0.0.1 - - [02/Jul/2017 22:50:31] Get2 request for tatvscapwii: {'hash': ['d814efa0880aec2d6ac2b2fc7a6de28a72c52e56'], 'pid': ['600259714'], 'data': ['aFtns4I8xyMcAAAA_wAAAAAAAAAFAAAADAAAAAEAAAACAAAAAAAAAA==']}
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 55010)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "gamestats_server.py", line 61, in do_GET
    self.server.gamestats_router.do_GET(self, gamename, path)
  File "/home/billy/services/HTTPGameStats/project/routers/__init__.py", line 31, in <lambda>
    self.do(handler, gamename, path, routes)
  File "/home/billy/services/HTTPGameStats/project/routers/__init__.py", line 39, in do
    return callback(handler, gamename, resource)
  File "/home/billy/services/HTTPGameStats/project/routers/web.py", line 404, in handle_web_client
    "put2.asp": client_put2
  File "/home/billy/services/HTTPGameStats/project/routers/web.py", line 379, in handle
    callback(handler, gamename, resource)
  File "/home/billy/services/HTTPGameStats/project/routers/web.py", line 259, in client_get2
    handler.server.gamestats_db
  File "/home/billy/services/HTTPGameStats/project/gamestats_database.py", line 215, in web_get2
    return db.web_get2(gamename, pid, region, category, mode, data)
  File "/home/billy/services/HTTPGameStats/project/gamestats_database.py", line 193, in web_get2
    raise ValueError("Unknown get2 mode: {}".format(mode))
ValueError: Unknown get2 mode: 5
----------------------------------------
```

**Comment by sepalani** [comment]
Was implemented (https://github.com/sepalani/GamestatsHTTP/commit/ae05797d1ca34878cf3f6e17bc2e0acfa9ff0fd3) and seems to work.
