### ISSUE TITLE
msolympicwii 98020

### ISSUE THREAD

**Issue by PokeAcer** [sepalani/GamestatsHTTP#24]
Server Log:
```
[msolympicwii] GET /web/client/get2.asp?pid=600259735
Key: GamestatsKey(salt='kyYszdUlxukYsLNpDHPJ', constants=GamestatsKeyConstants(x=229637, y=11551, z=131072, checksum_secret=389375694))
[msolympicwii] Handle get2.asp?pid=600259735
127.0.0.1 - - [03/Jul/2017 00:28:05] "GET /MSolympicwii/web/client/get2.asp?pid=600259735 HTTP/1.1" 200 -
[msolympicwii] GET /web/client/get2.asp?pid=600259735&hash=419f5762aeb2445c90ee79c2d851ee64afa8e703&data=FzVk0JY8xiMcAAEBBwAAABIBAAABAAABDAEBAAEAAQAeAQEBAQABAA==
Key: GamestatsKey(salt='kyYszdUlxukYsLNpDHPJ', constants=GamestatsKeyConstants(x=229637, y=11551, z=131072, checksum_secret=389375694))
[msolympicwii] Handle get2.asp?pid=600259735&hash=419f5762aeb2445c90ee79c2d851ee64afa8e703&data=FzVk0JY8xiMcAAEBBwAAABIBAAABAAABDAEBAAEAAQAeAQEBAQABAA==
127.0.0.1 - - [03/Jul/2017 00:28:06] Get2 request for msolympicwii: {'hash': ['419f5762aeb2445c90ee79c2d851ee64afa8e703'], 'pid': ['600259735'], 'data': ['FzVk0JY8xiMcAAEBBwAAABIBAAABAAABDAEBAAEAAQAeAQEBAQABAA==']}
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 37622)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "gamestats_server.py", line 61, in do_GET
    self.server.gamestats_router.do_GET(self, gamename, path)
  File "/home/billy/services/HTTPGameStats/project/routers/__init__.py", line 31, in <lambda>
    self.do(handler, gamename, path, routes)
  File "/home/billy/services/HTTPGameStats/project/routers/__init__.py", line 39, in do
    return callback(handler, gamename, resource)
  File "/home/billy/services/HTTPGameStats/project/routers/web.py", line 404, in handle_web_client
    "put2.asp": client_put2
  File "/home/billy/services/HTTPGameStats/project/routers/web.py", line 379, in handle
    callback(handler, gamename, resource)
  File "/home/billy/services/HTTPGameStats/project/routers/web.py", line 259, in client_get2
    handler.server.gamestats_db
  File "/home/billy/services/HTTPGameStats/project/gamestats_database.py", line 215, in web_get2
    return db.web_get2(gamename, pid, region, category, mode, data)
  File "/home/billy/services/HTTPGameStats/project/gamestats_database.py", line 193, in web_get2
    raise ValueError("Unknown get2 mode: {}".format(mode))
ValueError: Unknown get2 mode: 212925449
----------------------------------------
```

Rankings are top 30, and near my records (Maybe mode 5?).
PCAP: https://cdn.discordapp.com/attachments/219695042464317442/331229688385110019/wii.pcap

**Comment by sepalani** [comment]
It should be fixed by: https://github.com/sepalani/GamestatsHTTP/commit/0a03ae8a7ca4fbc4ef7c0370b1ba69de67de3759.
