### ISSUE TITLE
AttributeError during logging

### ISSUE THREAD

**Issue by obluda3** [sepalani/GamestatsHTTP#70]
After running the server for a while, an AttributeError exception happens, which forces us to restart the server completely.

Here is an example :

```
Exception happened during processing of request from ('ip', 15434)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 293, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 320, in handle_one_request
    if not self.parse_request():
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 253, in parse_request
    self.send_error(400, "Bad request version (%r)" % version)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 364, in send_error
    self.log_error("code %d, message %s", code, message)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 447, in log_error
    self.log_message(format, *args)
  File "gamestats_server.py", line 44, in log_message
    self.headers.get('x-forwarded-for', self.address_string()),
AttributeError: GamestatsHTTPRequestHandler instance has no attribute 'headers'
```

**Comment by sepalani** [comment]
@obluda3 
Thanks for the report, the issue should be fixed by https://github.com/sepalani/GamestatsHTTP/commit/c9b2bc1fd73163423c86c3a8f313031c654e5e77. Feel free to close the issue if it fixes your problems.
